name: Release Main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          target-branch: main

      - name: Create Release
        if: steps.release.outputs.release_created == 'true'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          release_name: ${{ steps.release.outputs.tag_name }}
          body: ${{ steps.release.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
